"""add_clients_tables

Revision ID: 04ecea0f8828
Revises: 4792ff4d87a5
Create Date: 2026-03-05 13:25:32.485638
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ecea0f8828'
down_revision: Union[str, None] = '4792ff4d87a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('servers',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('cpu_name', sa.String(), nullable=True),
    sa.Column('virtualization', sa.String(), nullable=True),
    sa.Column('arch', sa.String(), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('kernel_version', sa.String(), nullable=True),
    sa.Column('ipv4', sa.String(), nullable=True),
    sa.Column('ipv6', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('mem_total', sa.Integer(), nullable=True),
    sa.Column('swap_total', sa.Integer(), nullable=True),
    sa.Column('disk_total', sa.Integer(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('hidden', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servers_token'), ['token'], unique=True)

    op.create_table('server_groups',
    sa.Column('server_uuid', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_uuid'], ['servers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_uuid', 'group_id')
    )
    op.create_table('server_status',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_online', sa.Integer(), nullable=True),
    sa.Column('current_run_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['uuid'], ['servers.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.alter_column('success',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('timestamp',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'login'"))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('oauth_states', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'login'"))
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('success',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))

    op.drop_table('server_status')
    op.drop_table('server_groups')
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_token'))

    op.drop_table('servers')
    op.drop_table('groups')
    # ### end Alembic commands ###
