"""init_auth_tables

Revision ID: 4792ff4d87a5
Revises: 
Create Date: 2026-03-03 19:17:53.364483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4792ff4d87a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('attempt_type', sa.String(), nullable=True),
    sa.Column('success', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_ip_ts', ['ip_address', 'timestamp'], unique=False)

    op.create_table('oauth_states',
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), server_default=sa.text("'login'"), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('oidc',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('addition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('passwd', sa.String(), nullable=False),
    sa.Column('sso_type', sa.String(), nullable=True),
    sa.Column('sso_id', sa.String(), nullable=True),
    sa.Column('two_factor', sa.String(), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('sessions',
    sa.Column('session', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('login_method', sa.String(), nullable=True),
    sa.Column('latest_online', sa.Integer(), nullable=True),
    sa.Column('latest_user_agent', sa.String(), nullable=True),
    sa.Column('latest_ip', sa.String(), nullable=True),
    sa.Column('expires', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uuid'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_uuid'))

    op.drop_table('sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('oidc')
    op.drop_table('oauth_states')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_ip_ts')

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
