"""add_servers_top_and_is_approved

Revision ID: ae7f9b2df2e7
Revises: 04ecea0f8828
Create Date: 2026-03-05 14:28:54.439644
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7f9b2df2e7'
down_revision: Union[str, None] = '04ecea0f8828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('top', sa.Integer(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('is_approved', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers', schema=None) as batch_op:
        batch_op.drop_column('is_approved')
        batch_op.drop_column('top')

    # ### end Alembic commands ###
